OPTIONS(LOAD=-1,ROWS=-1,ERRORS=-1,DIRECT=y)
LOAD DATA
CHARACTERSET AL32UTF8
APPEND
INTO TABLE WK_SAP_OROSHI_HENV_IMP
TRAILING NULLCOLS
(
	TXT_DATA	CHAR(10000),
	LOAD_TS	CHAR(17) "TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3')",
	REC_NB	RECNUM
)