--確認用
-- MASTER
SELECT * 
FROM SYSTEM_CONTROL
WHERE SUBSYSTEM_ID IN ('COMMON', 'MASTER', 'URIAGE')
  AND PARAMETER_ID IN (
	'IF_CRM_PATH',
	'IF_CRM_BK_PATH',
	'IF_CRM_KYAKU_CD_ENCRYPT_KEY',
	'IF_CRM_SFTP_EXE',
	'IF_CRM_SFTP_HOST',
	'IF_CRM_SFTP_PORT',
	'IF_CRM_SFTP_LOGIN',
	'IF_CRM_SFTP_PASSWORD',
	'IF_CRM_SEND_DIR'
);
--変更用
DELETE SYSTEM_CONTROL
WHERE SUBSYSTEM_ID IN ('COMMON', 'MASTER', 'URIAGE')
  AND PARAMETER_ID IN (
	'IF_CRM_PATH',
	'IF_CRM_BK_PATH',
	'IF_CRM_KYAKU_CD_ENCRYPT_KEY',
	'IF_CRM_SFTP_EXE',
	'IF_CRM_SFTP_HOST',
	'IF_CRM_SFTP_PORT',
	'IF_CRM_SFTP_LOGIN',
	'IF_CRM_SFTP_PASSWORD',
	'IF_CRM_SEND_DIR'
);

INSERT INTO SYSTEM_CONTROL (SUBSYSTEM_ID, PARAMETER_ID, PARAMETER_TX, INSERT_TS, INSERT_USER_ID, UPDATE_TS, UPDATE_USER_ID) VALUES ('COMMON', 'IF_CRM_PATH', 'E:\mdware_mkh\datas\MKH\CRM', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX');
INSERT INTO SYSTEM_CONTROL (SUBSYSTEM_ID, PARAMETER_ID, PARAMETER_TX, INSERT_TS, INSERT_USER_ID, UPDATE_TS, UPDATE_USER_ID) VALUES ('MASTER', 'IF_CRM_BK_PATH', 'E:\mdware_mkh\datas\MKH\CRM\BK', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX');
INSERT INTO SYSTEM_CONTROL (SUBSYSTEM_ID, PARAMETER_ID, PARAMETER_TX, INSERT_TS, INSERT_USER_ID, UPDATE_TS, UPDATE_USER_ID) VALUES ('URIAGE', 'IF_CRM_KYAKU_CD_ENCRYPT_KEY', '0123456789ABCDEF', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX');
INSERT INTO SYSTEM_CONTROL (SUBSYSTEM_ID, PARAMETER_ID, PARAMETER_TX, INSERT_TS, INSERT_USER_ID, UPDATE_TS, UPDATE_USER_ID) VALUES ('MASTER', 'IF_CRM_SFTP_EXE', 'C:\SFTP\pscp.exe', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX');
INSERT INTO SYSTEM_CONTROL (SUBSYSTEM_ID, PARAMETER_ID, PARAMETER_TX, INSERT_TS, INSERT_USER_ID, UPDATE_TS, UPDATE_USER_ID) VALUES ('MASTER', 'IF_CRM_SFTP_HOST', '127.0.0.1', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX');
INSERT INTO SYSTEM_CONTROL (SUBSYSTEM_ID, PARAMETER_ID, PARAMETER_TX, INSERT_TS, INSERT_USER_ID, UPDATE_TS, UPDATE_USER_ID) VALUES ('MASTER', 'IF_CRM_SFTP_PORT', '22', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX');
INSERT INTO SYSTEM_CONTROL (SUBSYSTEM_ID, PARAMETER_ID, PARAMETER_TX, INSERT_TS, INSERT_USER_ID, UPDATE_TS, UPDATE_USER_ID) VALUES ('MASTER', 'IF_CRM_SFTP_LOGIN', 'user02', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX');
INSERT INTO SYSTEM_CONTROL (SUBSYSTEM_ID, PARAMETER_ID, PARAMETER_TX, INSERT_TS, INSERT_USER_ID, UPDATE_TS, UPDATE_USER_ID) VALUES ('MASTER', 'IF_CRM_SFTP_PASSWORD', 'user02', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX');
INSERT INTO SYSTEM_CONTROL (SUBSYSTEM_ID, PARAMETER_ID, PARAMETER_TX, INSERT_TS, INSERT_USER_ID, UPDATE_TS, UPDATE_USER_ID) VALUES ('MASTER', 'IF_CRM_SEND_DIR', 'data', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), 'VINX');

--確認用
-- MASTER
SELECT * 
FROM SYSTEM_CONTROL
WHERE SUBSYSTEM_ID IN ('COMMON', 'MASTER', 'URIAGE')
  AND PARAMETER_ID IN (
	'IF_CRM_PATH',
	'IF_CRM_BK_PATH',
	'IF_CRM_KYAKU_CD_ENCRYPT_KEY',
	'IF_CRM_SFTP_EXE',
	'IF_CRM_SFTP_HOST',
	'IF_CRM_SFTP_PORT',
	'IF_CRM_SFTP_LOGIN',
	'IF_CRM_SFTP_PASSWORD',
	'IF_CRM_SEND_DIR'
);

--コミット
COMMIT;